import { useTheme } from "styled-components";

import ProjectList from "./ProjectList";

const Projects = () => {
  const theme = useTheme();
  const facultyProjects = [
    {
      id: 13,
      title: theme.lang.projects.rank.title,
      subtitle: theme.lang.projects.rank.subtitle,
      date: theme.lang.projects.rank.date,
      filterTag: [{ name: theme.lang.projects.ac1it2, color: "lightPurple" }],
      skillsTag: [
        `NextJS`,
        `TypeScript`,
        `React JS`,
        `Tailwind CSS`,
        `Zustand`,
        `React Hook Form`,
        `Zod`,
        `Design system`,
      ],
      image: `rankCover.webp`,
      text: theme.lang.projects.rank.text,
      link: `https://rank-ifts24.netlify.app/`,
      gitHub: `https://github.com/vega-ifts24/rank_app`,
      comment: theme.lang.projects.rank.comment,
    },
    {
      id: 11,
      title: theme.lang.projects.bookers.title,
      subtitle: theme.lang.projects.bookers.subtitle,
      date: theme.lang.projects.bookers.date,
      filterTag: [
        { name: theme.lang.projects.ac1it2, color: "lightPurple" },
        { name: theme.lang.projects.ac1it3, color: "lightYellow" },
      ],
      skillsTag: [
        `Node.js`,
        `Express.js`,
        `MySQL`,
        `Multer`,
        `JWT`,
        `TypeScript`,
        `Postman`,
        `API REST`,
        `GitHub`,
        `VSCode`,
        `Vercel`,
        `AlwaysData`,
        `NextJS`,
        `TailwindCSS`,
      ],
      image: `bookersCover.webp`,
      text: theme.lang.projects.bookers.text,
      link: `https://bookreview-ifts24.vercel.app/`,
      gitHub: `https://github.com/nataliacamilavega/back-tp-bookreview`,
      comment: theme.lang.projects.bookers.comment,
    },
  ];
  const courseProjects = [
    {
      id: 8,
      title: theme.lang.projects.beautyCosmetics.title,
      subtitle: theme.lang.projects.beautyCosmetics.subtitle,
      date: theme.lang.projects.beautyCosmetics.date,
      filterTag: [{ name: theme.lang.projects.ac1it2, color: "lightPurple" }],
      skillsTag: [
        `HTML5`,
        `CSS3`,
        `JavaScript`,
        `React JS`,
        `Responsive design`,
        `Firebase`,
        `VSCode`,
        `GitHub`,
      ],
      image: `coderReactProject.webp`,
      text: theme.lang.projects.beautyCosmetics.text,
      gitHub: `https://github.com/nataliavega98/Beauty-Cosmetics`,
      link: `https://beautycosmetics.vercel.app/`,
      comment: theme.lang.projects.beautyCosmetics.comment,
    },
    {
      id: 7,
      title: theme.lang.projects.gamingStore.title,
      subtitle: theme.lang.projects.gamingStore.subtitle,
      date: theme.lang.projects.gamingStore.date,
      filterTag: [{ name: theme.lang.projects.ac1it2, color: "lightPurple" }],
      skillsTag: [
        `HTML5`,
        `CSS3`,
        `JS Vanilla`,
        `Responsive design`,
        `APIs`,
        `VSCode`,
        `GitHub`,
      ],
      image: `nucbaJSProject.webp`,
      text: theme.lang.projects.gamingStore.text,
      gitHub: `https://github.com/nataliavega98/gaming-store`,
      link: `https://gamingstore-bynatalia.vercel.app/`,
      comment: theme.lang.projects.gamingStore.comment,
    },
    {
      id: 6,
      title: theme.lang.projects.limsa.title,
      subtitle: theme.lang.projects.limsa.subtitle,
      date: theme.lang.projects.limsa.date,
      filterTag: [{ name: theme.lang.projects.ac1it1, color: "lightPink" }],
      skillsTag: [
        `Prototipado`,
        `Responsive Design`,
        `UI Kit`,
        `Benchmarking`,
        `Aplicación móvil`,
        `Whimsical`,
        `UXTweak`,
        `Ps`,
      ],
      image: `coderLIMSAProject.webp`,
      text: theme.lang.projects.limsa.text,
      behance: `https://www.behance.net/gallery/159075451/LIM-SA-Landing-page`,
      link: `https://lim-sa.netlify.app/`,
      comment: theme.lang.projects.limsa.comment,
    },
    {
      id: 5,
      title: theme.lang.projects.hbomax.title,
      subtitle: theme.lang.projects.hbomax.subtitle,
      date: theme.lang.projects.hbomax.date,
      filterTag: [{ name: theme.lang.projects.ac1it1, color: "lightPink" }],
      skillsTag: [
        `Prototipado`,
        `Responsive Design`,
        `UI Kit`,
        `Benchmarking`,
        `Diseño web`,
        `Whimsical`,
        `UXTweak`,
        `Ps`,
      ],
      image: `coderUXAProject.webp`,
      text: theme.lang.projects.hbomax.text,
      behance: `https://www.behance.net/gallery/150898443/Re-diseno-de-la-web-HBO-MAX-Natalia-Vega`,
      comment: theme.lang.projects.hbomax.comment,
    },
    {
      id: 4,
      title: theme.lang.projects.gina.title,
      subtitle: theme.lang.projects.gina.subtitle,
      date: theme.lang.projects.gina.date,
      filterTag: [
        { name: theme.lang.projects.ac1it1, color: "lightPink" },
        { name: theme.lang.projects.ac1it2, color: "lightPurple" },
      ],
      skillsTag: [
        `Prototipado`,
        `Responsive Design`,
        `Figma`,
        `HTML5`,
        `CSS3`,
        `Diseño web`,
        `VSCode`,
        `Ps`,
      ],
      image: `ginaProject.webp`,
      text: theme.lang.projects.gina.text,
      link: `https://gina-unaperritamuydulce.vercel.app/`,
      comment: theme.lang.projects.gina.comment,
    },
    {
      id: 3,
      title: theme.lang.projects.vf.title,
      subtitle: theme.lang.projects.vf.subtitle,
      date: theme.lang.projects.vf.date,
      filterTag: [{ name: theme.lang.projects.ac1it1, color: "lightPink" }],
      skillsTag: [
        `Prototipado`,
        `Responsive Design`,
        `Figma`,
        `UI Kit`,
        `Benchmarking`,
        `Whimsical`,
        `UXTweak`,
      ],
      image: `coderVFProject.webp`,
      text: theme.lang.projects.vf.text,
      behance: `https://www.behance.net/gallery/153206055/Reporte-UX-VF-Natalia-Vega?tracking_source=project_owner_other_projects/`,
      comment: theme.lang.projects.vf.comment,
    },
    {
      id: 2,
      title: theme.lang.projects.nereidas.title,
      subtitle: theme.lang.projects.nereidas.subtitle,
      date: theme.lang.projects.nereidas.date,
      filterTag: [{ name: theme.lang.projects.ac1it2, color: "lightPurple" }],
      skillsTag: [
        `HTML5`,
        `CSS3`,
        `Diseño web`,
        `Responsive design`,
        `Maquetado`,
        `VSCode`,
      ],
      image: `nucbaDWebProject.webp`,
      text: theme.lang.projects.nereidas.text,
      link: `https://nereidas-cruceros.vercel.app/`,
      comment: theme.lang.projects.nereidas.comment,
    },
    {
      id: 1,
      title: theme.lang.projects.share.title,
      subtitle: theme.lang.projects.share.subtitle,
      date: theme.lang.projects.share.date,
      filterTag: [{ name: theme.lang.projects.ac1it1, color: "lightPink" }],
      skillsTag: [
        `Prototipado`,
        `Figma`,
        `UI Kit`,
        `Benchmarking`,
        `Aplicación móvil`,
        `Whimsical`,
        `Optimal Workshop`,
        `Ps`,
        `Ai`,
      ],
      image: `coderUXProject.webp`,
      text: theme.lang.projects.share.text,
      behance: `https://www.behance.net/gallery/142527049/Share-Natalia-Vega`,
      comment: theme.lang.projects.share.comment,
    },
  ];

  const personalProjects = [
    {
      id: 20,
      title: theme.lang.projects.examenConducir.title,
      subtitle: theme.lang.projects.examenConducir.subtitle,
      date: theme.lang.projects.examenConducir.date,
      filterTag: [{ name: theme.lang.projects.ac1it2, color: "lightPurple" }],
      skillsTag: [`NextJS`, `TypeScript`, `React JS`, `Tailwind CSS`, `SEO`],
      image: `examenConducirCover.webp`,
      text: theme.lang.projects.examenConducir.text,
      link: `https://examendeconducir.com.ar/`,
      comment: theme.lang.projects.examenConducir.comment,
    },
  ];
  const withContext = (items, context) =>
    items.map((item) => ({ ...item, context }));
  const [rank, bookers] = facultyProjects;
  const collection = [
    ...withContext(personalProjects, theme.lang.projects.personal),
    ...withContext([rank], theme.lang.projects.faculty),
    ...withContext([bookers], theme.lang.projects.faculty),
    ...withContext(courseProjects, theme.lang.projects.courses),
  ];

  return (
    <ProjectList
      collection={collection}
      title={theme.lang.projects.h2}
      titleColor="blue"
      withContext
    />
  );
};

export default Projects;
